spring:
  rabbitmq:
  ####连接地址
    host: 127.0.0.1
   ####端口号   
    port: 5672
   ####账号 
    username: user
   ####密码  
    password: 123456
   ### 地址
    virtual-host: /huihuang

server:
  port: 8002